### ISSUE TITLE
Seems to have stopped working in flutter 3.0

### ISSUE THREAD

**Issue by LeeMatthewHiggins** [SachinGanesh/screenshot#102]
This code used to work on flutter https://github.com/flutter/flutter/releases/tag/2.10.5
but just gives a transparent image on https://github.com/flutter/flutter/releases/tag/3.0.0

```
 final pngData =
        await ScreenshotController().captureFromWidget(widget, pixelRatio: 5.0);
```

**Comment by aytunch** [comment]
I have the same problem. I have no idea what the cause is.
@SachinGanesh can you please look in to this issue? This blocks us from upgrading to Flutter 3.0
By the way thanks for this awesome package.

**Comment by steffenSuess** [comment]
I think the problem is related to the migration to the web ImageDecoder API as described [here](https://github.com/flutter/flutter/issues/97103#issuecomment-1024789252). I was able to temporarily solve it for myself by setting the flag described [here](https://github.com/flutter/flutter/issues/97103#issuecomment-1024701675).

`flutter run -d chrome --dart-define=BROWSER_IMAGE_DECODING_ENABLED=false --release`

**Comment by aytunch** [comment]
@steffenSuess thanks for the workaround suggestion. I hope a persistent solution arrives.
Best regards

**Comment by ritheshSalyan** [comment]
for Reference [https://github.com/SachinGanesh/screenshot/issues/103](https://github.com/SachinGanesh/screenshot/issues/103)
