### ISSUE TITLE
Issue with google maps

### ISSUE THREAD

**Issue by A-EL** [SachinGanesh/screenshot#11]
Hello,
I tried using this plugin with a widget with google maps in it. It captures the screen but without the maps part. It appears blank.
Appreciate if you can help.

Thanks

**Comment by SachinGanesh** [comment]
Hi, Maps will take some time to render. please use the **delay** parameter in capture method. this issue is discussed here https://github.com/SachinGanesh/screenshot/issues/9

**Comment by pinkeshAubergine** [comment]
@SachinGanesh I have tried setting the delay of 20 Seconds but the problem is still there. Could you please look into this.

I am having full-screen google map and I am getting result like this. The complete blank screen.
![Issue_20191004_150313](https://user-images.githubusercontent.com/56068831/66197678-8b7b5f00-e6b8-11e9-916d-ad7ae407b117.png)

**Comment by jsamples** [comment]
Has there been any progress with this issue? We are experiencing the same issue with google maps

**Comment by sanekyy** [comment]
Hey. I faced with the same problem when try to caprure screenshot from video_view.
So I think this problem related with platform view.

**Comment by SachinGanesh** [comment]
Yes. I did some testing. Its the issue with the Platform View not getting rendered while taking the screenshot.

**Comment by sanekyy** [comment]
So, do you have an idea how to get screenshot of Platform View?

**Comment by pinkeshAubergine** [comment]
@SachinGanesh Could you please suggest any workaround for this?

**Comment by bwhiteTP** [comment]
I am also interested in a solution for this.

**Comment by toonztudio** [comment]
I can confirm this issue.
I found this problem when make a screenshot of camera too?

**Comment by sanekyy** [comment]
> I can confirm this issue.
> I found this problem when make a screenshot of camera too?

This issue is related to platform views

**Comment by CoderJava** [comment]
Any update on this issue?

**Comment by CoderJava** [comment]
I fixed it with use this plugin
[native_screenshot](https://pub.dev/packages/native_screenshot)

**Comment by ritheshSalyan** [comment]
we cannot capture platform views because of [https://github.com/flutter/flutter/issues/25306](https://github.com/flutter/flutter/issues/25306). but for google maps, you have a method named takeScreenshot maps plugin. more info check this [issue](https://github.com/ueman/feedback/issues/11#issuecomment-603730147)

**Comment by harlanx** [comment]
In my case I needed to combine other widgets and google map in a screenshot. So what I did is wrap google map widget and a visibility widget with Image.memory in a Stack so whenever a screenshot function is executed, the .takeSnapshot method of google maps will provide the Uint8List for Image.memory widget then set the visibility to true and returns to false when it is done.
