### ISSUE TITLE
arguments don't match.   const ViewConfiguration({  No named parameter with the name 'size'.

### ISSUE THREAD

**Issue by SameerGhaffar** [SachinGanesh/screenshot#167]
I got this error message

/C:/Users/samee/AppData/Local/Pub/Cache/hosted/pub.dev/screenshot-2.1.0/lib/screenshot.dart:168:9: Error: No named parameter with the name 'size'.
        size: logicalSize,
        ^^^^
/C:/src/flutter/packages/flutter/lib/src/rendering/view.dart:28:9: Context: Found this candidate, but the arguments don't match.
  const ViewConfiguration({
        ^^^^^^^^^^^^^^^^^
Target kernel_snapshot failed: Exception

FAILURE: Build failed with an exception.

* Where:
Script 'C:\src\flutter\packages\flutter_tools\gradle\src\main\groovy\flutter.groovy' line: 1629

* What went wrong:
Execution failed for task ':app:compileFlutterBuildDebug'.
> Process 'command 'C:\src\flutter\bin\flutter.bat'' finished with non-zero exit value 1

* Try:
> Run with --stacktrace option to get the stack trace.
> Run with --info or --debug option to get more log output.
> Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 5m 11s
Error: Gradle task assembleDebug failed with exit code 1

**Comment by ritheshSalyan** [comment]
Hi,
This issue occurred because of some API Changes in Flutter. 

So, We have released 2 new versions :

[2.2.0](https://pub.dev/packages/screenshot/versions/2.2.0) - Use this version if you are in the beta/master channel.
[2.3.0](https://pub.dev/packages/screenshot/versions/2.2.0) - Use this version if you are in the Stable channel.

Closing this issue. If you think it is incorrect, Please feel free to reopen this issue
