### ISSUE TITLE
Is it work in Webview?

### ISSUE THREAD

**Issue by izzabellerina** [SachinGanesh/screenshot#26]
I have been trying to screen capture a picture of  WebView and the result that I get is an empty picture. Do you have a solution to solve them? I had no error in the command line, it only sent me an empty picture. Thank you in advance.

**Comment by SachinGanesh** [comment]
This feature is currenly not available for the Web. https://github.com/flutter/engine/pull/20750 solves this problem. Should wait till this fix is released to the stable branch

**Comment by peterlauri** [comment]
The mentioned issue was merged to master 2nd of September. I don't find a good way to actually figure out if it has reached stable or not.

**Comment by izzabellerina** [comment]
> This feature is currenly not available for the Web. [flutter/engine#20750](https://github.com/flutter/engine/pull/20750) solves this problem. Should wait till this fix is released to the stable branch

Thank you so much

**Comment by ritheshSalyan** [comment]
We cannot capture platform views because of the issue [https://github.com/flutter/flutter/issues/25306](https://github.com/flutter/flutter/issues/25306). but you can use [https://pub.dev/packages/flutter_inappwebview](https://pub.dev/packages/flutter_inappwebview) package. it provides a method  **takeScrenshoot**  to take screenshot of webview.

you can find same method in google_maps as well

**Comment by dayron9110** [comment]
News?

**Comment by ritheshSalyan** [comment]
Closing in favour of https://github.com/SachinGanesh/screenshot/issues/62

**Comment by bahman2000** [comment]
@ritheshSalyan The `takeScreenshot ` method in the `inappwebview ` package only captures the part of the content visible on the device screen, not the entire content of the WebView.

**Comment by ritheshSalyan** [comment]
Yes, but we can't capture native view.

**Comment by bahman2000** [comment]
@SachinGanesh I’m still getting an empty picture in output, even with the latest version of Flutter and the latest version of the package.

**Comment by bahman2000** [comment]
@ritheshSalyan Could you please explain a bit more?

**Comment by ritheshSalyan** [comment]
Yes, sure. 

We cannot capture screenshot of a platform view due to flutter limitations. So if you are trying to screenshot a platform view(Like webview, maps view, etc) using this plugin then you will get black image. 

So for this, some webview and maps plugins provide capture image methods. They capture screenshot of widget and return you as image. If you face any issues in thier methods, then please file issues in respective plugin repositories.
