### ISSUE TITLE
How to capture widget that is not in tree using compute function?

### ISSUE THREAD

**Issue by arzakmiftakhul** [SachinGanesh/screenshot#98]
I want to capture complex and high resolution widget that is not in tree. It works but freezes the UI if I use main thread, so I want to use isolated thread/compute function.

This is simple code you can try to reproduce.
```
Future<Uint8List>captureWidget(String value) async {
    ScreenshotController screenshotController = ScreenshotController();
    return await screenshotController.captureFromWidget(Text(value));
}
```
then call
```
    Uint8List capturedWidget = await compute(captureWidget,"Test");
```
I got this error
```
[ERROR:flutter/lib/ui/ui_dart_state.cc(209)] Unhandled Exception: Exception: 'dart:ui/window.dart': Failed assertion: line 298 pos 12: '<optimized out>': is not true.
```

**Comment by ritheshSalyan** [comment]
Hello @arzakmiftakhul  , 
   
 The error can be solved by giving `targetSize` parameter, but 
  Unfortunately, you cannot do any UI actions in isolates. Please check this issue [https://github.com/flutter/flutter/issues/10647](https://github.com/flutter/flutter/issues/10647), Due to this capturing widgets from isolate is not possible now.

**Comment by spauldhaliwal** [comment]
See this https://github.com/SachinGanesh/screenshot/issues/120#issuecomment-1780166874
